# Generated by Django 5.0.2 on 2024-04-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideshow/images')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
