# Generated by Django 5.0.2 on 2024-04-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_research_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
