# Generated by Django 5.0.2 on 2024-04-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0003_alter_slideshow_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
