# Generated by Django 5.0.2 on 2024-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0004_alter_research_link_alter_slideshow_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.ImageField(upload_to='static/Images'),
        ),
    ]
