# Generated by Django 5.0.2 on 2024-04-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0005_alter_slideshow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
