# Generated by Django 5.0.2 on 2024-04-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0007_alter_research_image_alter_slideshow_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Field1', models.CharField(max_length=200)),
                ('Field2', models.CharField(max_length=200)),
                ('Field3', models.CharField(max_length=200)),
                ('Field4', models.CharField(max_length=200)),
            ],
        ),
    ]
