# Generated by Django 5.0.2 on 2024-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0008_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='Field1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='Field2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='Field3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='Field4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
