# Generated by Django 5.0.2 on 2024-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0009_alter_achievement_field1_alter_achievement_field2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='Field1Desc',
            field=models.CharField(default='Happy customers', max_length=200),
        ),
        migrations.AddField(
            model_name='achievement',
            name='Field2Desc',
            field=models.CharField(default='Happy customers', max_length=200),
        ),
        migrations.AddField(
            model_name='achievement',
            name='Field3Desc',
            field=models.CharField(default='Projects completed', max_length=200),
        ),
        migrations.AddField(
            model_name='achievement',
            name='Field4Desc',
            field=models.CharField(default='Awwards Won', max_length=200),
        ),
    ]
