# Generated by Django 5.0.2 on 2024-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0011_alter_research_image_alter_slideshow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='Field2Desc',
            field=models.CharField(default='Issues Solved', max_length=200),
        ),
    ]
