# Generated by Django 5.0.2 on 2024-05-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0012_alter_achievement_field2desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
