# Generated by Django 5.0.2 on 2024-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0013_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
